# Required VARS:
#   - rails_app_first_run
#
---
- name: check if haproxyctl is installed
  stat: >
    path=/etc/init.d/haproxyctl
  register: haproxyctl
  when: rails_app_first_run

- name: set haproxyctl_is_installed
  set_fact:
    haproxyctl_is_installed: haproxyctl.stat.exists
  when: rails_app_first_run
